# Generated by Django 3.2.10 on 2022-01-03 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employees',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_name', models.CharField(max_length=120)),
                ('designation', models.CharField(max_length=120)),
                ('salary', models.PositiveIntegerField()),
                ('address', models.CharField(max_length=120)),
                ('email', models.CharField(max_length=120, unique=True)),
                ('phone', models.CharField(max_length=15, unique=True)),
            ],
        ),
    ]
