# Generated by Django 3.2.10 on 2022-01-03 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_alter_employees_designation'),
    ]

    operations = [
        migrations.AddField(
            model_name='employees',
            name='is_active',
            field=models.BooleanField(default=True, null=True),
        ),
    ]
